services:
  web:
    build:
      context: ../..
      dockerfile: config/docker/Dockerfile
    command: ["./entrypoint.sh"]
    env_file:
      - ../../.env
    ports:
      - "${PORT:-8000}:8000"
    volumes:
      - ../..:/app
    restart: always
